---
title: "Target_Data_comp"
output: html_document
date: "2026-03-15"
---

```{r}
library(tidyverse)
library(dataRetrieval)
library(ggpmisc)
```



## Get daily Q from HPB PT

```{r}
hpb_stage_EDI <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/2333/1/630f42ffb3560c3a6afd592511756c1e")

# daily_Q <- hpb_stage_EDI |> 
#   mutate(Date = as.Date(DateTime)) |> 
#   group_by(Date) |> 
#   summarise(Q_cms_PT = mean(Flow_cms, na.rm = T)) |> 
#   mutate(Q_L_s_PT = Q_cms_PT * 1000) |> 
#   select(Date, Q_L_s_PT)

daily_Q <- hpb_stage_EDI |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(Q_cms_PT = mean(Flow_cms, na.rm = T)) |> 
  mutate(Q_m3day_PT = Q_cms_PT * 86400) |> 
  select(Date, Q_m3day_PT)


```

## USGS

```{r}
#### Daily Q for Tinker 
ref_site <- "02055100"

USGS_daily <- readNWISdv(
  siteNumbers = ref_site,
  parameterCd = "00060",          # discharge in cfs
  startDate = "2010-01-01",
  endDate   = "2026-04-01"
) |>
  renameNWISColumns()  

USGS_Ref <- USGS_daily |>
  mutate(Tinker_Flow_cms = Flow / 35.3, #cfs to cms
         Tinker_Flow_m3_day = Tinker_Flow_cms * 86400 ) |> 
  select(Date, Tinker_Flow_m3_day)


##Regress Tinker to HPB
usgs_hbp_Q <- full_join(USGS_Ref, daily_Q) 

usgs_hbp_Q_filt <- usgs_hbp_Q |> 
  filter(Date < ymd("2025-04-01")) 

usgs_hbp_Q_filt |> 
    ggplot(aes(x = (Tinker_Flow_m3_day), y = (Q_m3day_PT)))+
  geom_point()+
  #scale_y_log10()+
  stat_poly_line(method = "lm", linewidth = 2) +
  stat_poly_eq(formula = y ~ x, label.x = "left", label.y = "top", parse = TRUE,
    inherit.aes = FALSE, aes(x = Tinker_Flow_m3_day, y = Q_m3day_PT,
        label = paste(..adj.rr.label.., ..p.value.label.., sep = "~~~"), size = 3)  ) +
  theme_bw()


lm_tinker <- lm(Q_m3day_PT ~ Tinker_Flow_m3_day, data = usgs_hbp_Q_filt)
summary(lm_tinker)
lm_tinker

usgs_hbp_Q <- usgs_hbp_Q |> 
  mutate(HPB_Q_lm_m3day = predict(lm_tinker, newdata = usgs_hbp_Q))


usgs_hbp_Q |> 
  filter(Date > ymd("2024-05-01")) |> 
  select(Date, Q_m3day_PT, HPB_Q_lm_m3day) |> 
  pivot_longer(-1) |> 
  ggplot(aes(x = Date, y = value, col = name))+ geom_point()


##set up data to write
dailyQ_hpb <- usgs_hbp_Q |> 
  filter(Date >= ymd("2019-01-01")) |> 
  mutate(Site = 100) |> 
  select(Site, Date, Q_m3day_PT, HPB_Q_lm_m3day) |> 
  rename(HPB_Q_PT_m3day = Q_m3day_PT)


```


## Get Flowmate observations

```{r}
flowmate_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/454/9/0e7fe16623a1ad2a67774c23ce8a29d8")

# hpb_flowmate <- flowmate_edi |> 
#   filter(Reservoir == "CCR", Site %in% c(101, 100)) |> 
#   mutate(Date = as.Date(DateTime)) |> 
#   dplyr::select(Date, Flow_cms) |> 
#   dplyr::rename(Q_cms_Flowmate = Flow_cms) |> 
#   mutate(Q_L_s_Flowmate = Q_cms_Flowmate * 1000) |> 
#   select(Date, Q_L_s_Flowmate)

stream_flowmate <- flowmate_edi |>
filter(Reservoir == "CCR",
         Site %in% c(101, 100, 301, 300, 201, 200)) |>
  mutate(Site = ifelse(Site %in% c(101,100), 100, Site),
         Site = ifelse(Site %in% c(301,300), 300, Site),
         Site = ifelse(Site %in% c(201,200), 200, Site)
         ) |> 
  mutate(Date = as.Date(DateTime)) |>
  dplyr::select(Date, Site, Flow_cms) |>
  dplyr::rename(Q_cms_Flowmate = Flow_cms) |>
  mutate(Q_L_s_Flowmate = Q_cms_Flowmate * 1000,
         Q_m3day_flowmate = Q_cms_Flowmate * 86400) |>
  select(Date, Site, Q_m3day_flowmate)

```


## Get stream chem

```{r}
chem_EDI <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/199/13/3f09a3d23b7b5dd32ed7d28e9bc1b081")


# hpb_chem <- chem_EDI |> 
#   mutate(Date = as.Date(DateTime)) |> 
#   filter(Reservoir == "CCR",
#          Site %in% c(101, 100)) |>
#   select(Reservoir, Site, Date, Depth_m, Rep, DOC_mgL, DN_mgL, NO3NO2_ugL, NH4_ugL, SRP_ugL, TN_ugL, TP_ugL) |> 
#   group_by(Date) |> 
#   summarise(across(c(DOC_mgL, DN_mgL, NO3NO2_ugL, NH4_ugL, SRP_ugL, TN_ugL, TP_ugL), mean, na.rm = TRUE)) |> 
#   mutate(DON_mgL = DN_mgL - ((NO3NO2_ugL + NH4_ugL)/1000)) |> 
#   #make all mg/L and drop P for now
#   mutate(NO3_mgL = NO3NO2_ugL / 1000,
#          NH4_mgL = NH4_ugL/1000,
#          TN_mgL = TN_ugL/1000) |> 
#   #round to 3 decimals 
#   pivot_longer(-1) |> 
#   mutate(value = round(value, 3)) |> 
#   pivot_wider(names_from = name, values_from = value) |> 
#   select(Date, DOC_mgL, DON_mgL, NO3_mgL, NH4_mgL)
#   #select(Date, DOC_mgL, DON_mgL, NO3_mgL, NH4_mgL, DN_mgL, TN_mgL)


stream_chem <- chem_EDI |> 
  mutate(Date = as.Date(DateTime)) |> 
  filter(Reservoir == "CCR",
         Site %in% c(101, 100, 301, 300, 201, 200)) |>
  mutate(Site = ifelse(Site %in% c(101,100), 100, Site),
         Site = ifelse(Site %in% c(301,300), 300, Site),
         Site = ifelse(Site %in% c(201,200), 200, Site)
         ) |> 
  select(Reservoir, Site, Date, Depth_m, Rep, DOC_mgL, DN_mgL, NO3NO2_ugL, NH4_ugL, SRP_ugL, TN_ugL, TP_ugL) |> 
  group_by(Date, Site) |> 
  summarise(across(c(DOC_mgL, DN_mgL, NO3NO2_ugL, NH4_ugL, SRP_ugL, TN_ugL, TP_ugL), mean, na.rm = TRUE)) |> 
  mutate(DON_mgL = DN_mgL - ((NO3NO2_ugL + NH4_ugL)/1000)) |> 
  #make all mg/L and drop P for now
  mutate(NO3_mgL = NO3NO2_ugL / 1000,
         NH4_mgL = NH4_ugL/1000,
         TN_mgL = TN_ugL/1000) |> 
  #round to 3 decimals 
  pivot_longer(-c(1:2)) |> 
  mutate(value = round(value, 3)) |> 
  pivot_wider(names_from = name, values_from = value) |> 
  select(Date, Site, DOC_mgL, DON_mgL, NO3_mgL, NH4_mgL)
  #select(Date, DOC_mgL, DON_mgL, NO3_mgL, NH4_mgL, DN_mgL, TN_mgL)


```
STREAM SYNOPTIC

```{r}
stream_synoptic <- full_join(stream_chem, stream_flowmate, by = c("Date", "Site"))

# write.csv(stream_synoptic, "./StreamSynoptic_2020_2025.csv", row.names = F)

stream_synoptic |> 
  mutate(year = year(Date)) |> filter(year == 2022) |> 
  ggplot(aes(x=Date, y = Q_m3day_flowmate, color = as.factor(Site)))+
  geom_point() + scale_y_log10()


stream_synoptic |> 
  select(-Q_m3day_flowmate) |> 
  pivot_longer(-c(1:2)) |> 
  ggplot(aes( x= Site, y = value, color = as.factor(Site), group = Site))+
  geom_point()+geom_boxplot()+
  facet_wrap(~name, scales = "free_y")


```



## Get MODIS LAI DATA 

```{r}

# hpb_lat <- 37.3646
# hpb_long <- -79.9733
# ## GET LAI data following Quinn's code
# #https://frec-5174.github.io/eco4cast-in-R-book/neon-data.html#modis-lai
# library(MODISTools)
# lai <- MODISTools::mt_subset(product = "MCD15A2H",
#                   lat = hpb_lat,
#                   lon =  hpb_long,
#                   band = c("Lai_500m", "FparLai_QC"),
#                   start = as_date("2000-01-01"),
#                   end = Sys.Date(),
#                   site_name = "HPB",
#                   progress = FALSE)
# 
# 
# lai_cleaned <- lai |> 
#   mutate(scale = ifelse(band == "FparLai_QC", 1, scale),
#          scale = as.numeric(scale),
#          value = scale * value,
#          datetime = lubridate::as_date(calendar_date)) |> 
#   select(band, value, datetime) |> 
#   pivot_wider(names_from = band, values_from = value) |> 
#   filter(FparLai_QC == 0) |> 
#   rename(observation = Lai_500m) |> 
#   mutate(variable = "lai") |> 
#   select(datetime, variable, observation)
# 
# 
# 
# ### plot lai
# lai_cleaned <- lai_cleaned |> 
#   pivot_wider(names_from = variable, values_from = observation) |> 
#   rename(lai_MODIS = lai)
# 
# lai_cleaned |> ggplot(aes(x = datetime, y = lai_MODIS))+ geom_point()+geom_line()
# 
# 
# write.csv(lai_cleaned, "./LAI_modisData_nov2002_jan2026.csv", row.names = F)
# 
# lai <- read_csv("./LAI_modisData_nov2002_jan2026.csv") |> 
#   rename(Date = datetime)

lai <- read_csv("C:/Users/dwh18/OneDrive/Desktop/R_Projects/RHESSys_Tutorial/Target_Data_comp/LAI_modisData_nov2002_jan2026.csv")|> 
  rename(Date = datetime) |> 
  mutate(Site = 101)


```


##join data together

```{r}

# df_join <- full_join(daily_Q, hpb_flowmate, by = "Date") |> 
#   full_join(lai, by = "Date") |> 
#   full_join(hpb_chem, by = "Date") |> 
#   arrange(Date) |> 
#   filter(Date >= ymd("2020-01-01"))
# 
# 
# write.csv(df_join, "./TargetData_2020_2025.csv", row.names = F)

head(stream_synoptic)
head(dailyQ_hpb)

df_join <- full_join(dailyQ_hpb, stream_synoptic, by = c("Date", "Site")) |> 
  full_join(lai, by = c("Date", "Site")) |> 
  arrange(Date) 

write.csv(df_join, "./TargetData_2020_2025.csv", row.names = F)


```







